In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Q1. Which dataset are you using for this exam?

In [3]:
data=pd.read_csv('/content/drive/MyDrive/Data/NPPE2_Preprocessing_Dataset_V1.csv')

In [4]:
data.head()

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation,LivesIn,GlucoseLevel,BMI,SmokingStatus,HeartAttack
0,Female,75.0,Yes,No,Yes,Self-employed,City,54.6,35.1,never smoked,No
1,Female,49.0,No,No,Yes,Private,Village,108.8,26.7,smokes,No
2,Male,32.0,No,No,Yes,Private,City,64.1,23.4,smokes,No
3,Male,78.0,No,No,Yes,Self-employed,City,219.2,27.4,Unknown,Yes
4,Male,39.0,No,No,Yes,Private,City,55.4,41.6,formerly smoked,No

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           4000 non-null   object
 1   Age              4000 non-null   float64
 2   HasTension       4000 non-null   object
 3   AnyHeartDisease  4000 non-null   object
 4   NeverMarried     4000 non-null   object
 5   Occupation       4000 non-null   object
 6   LivesIn          4000 non-null   object
 7   GlucoseLevel     4000 non-null   float64
 8   BMI              3851 non-null   float64
 9   SmokingStatus    4000 non-null   object
 10  HeartAttack      4000 non-null   object
dtypes: float64(3), object(8)
memory usage: 343.9+ KB

In [6]:
data.isnull().sum()

Gender               0
Age                  0
HasTension           0
AnyHeartDisease      0
NeverMarried         0
Occupation           0
LivesIn              0
GlucoseLevel         0
BMI                149
SmokingStatus        0
HeartAttack          0
dtype: int64

In [7]:
columns= data.columns

In [8]:
for c in columns:
  a=data[c].unique()
  print(a)

['Female' 'Male' 'Unknown']
[ 7.50e+01  4.90e+01  3.20e+01  7.80e+01  3.90e+01 -3.00e+00  6.30e+01
  4.00e+00  4.50e+01  5.20e+01  3.10e+01  5.70e+01  5.60e+01  2.00e+01
  2.40e-01  3.80e+01  8.20e+01  3.40e+01  2.90e+01  1.60e+01  7.00e+00
  3.70e+01  5.10e+01  2.60e+01  5.30e+01  5.00e+01  2.00e+00  5.40e+01
  7.90e+01  6.00e+00  5.80e+01  6.50e+01  1.30e+01  4.70e+01  1.90e+01
  7.40e+01  7.30e+01  1.20e+01  9.00e+00  2.70e+01  3.30e+01  8.10e+01
  3.60e+01  7.60e+01  7.10e+01  4.60e+01  2.50e+01  1.70e+01  2.20e+01
  1.10e+01  5.50e+01  6.10e+01  6.90e+01  7.70e+01  4.20e+01  2.40e+01
  7.20e+01  3.50e+01  8.00e+01  1.64e+00  5.90e+01  6.00e+01  4.10e+01
  4.30e+01  6.20e+01  6.40e+01  5.00e+00  7.00e+01  2.10e+01  1.00e+01
  1.80e+01  1.40e+01  4.00e+01  1.50e+01  3.00e+00  4.80e+01  8.00e+00
  1.32e+00  6.70e+01  4.40e+01  6.80e+01  1.56e+00  2.30e+01  6.60e+01
  8.00e-01  3.00e+01  1.88e+00  2.80e+01  5.60e-01  6.40e-01  3.20e-01
  1.80e+00  1.60e-01  7.20e-01  1.40e+00  8.80e-01  1.08e+00  1.72e+00
  1.24e+00  4.00e-01  1.00e+00  1.48e+00  4.80e-01  8.00e-02  1.16e+00]
['Yes' 'No']
['No' 'Yes']
['Yes' 'No']
['Self-employed' 'Private' 'children' 'Govt_job' 'Never_worked']
['City' 'Village' 'Unknown']
[ 54.6 108.8  64.1 ... 218.9  66.3 168.5]
[35.1 26.7 23.4 27.4 41.6 29.3 37.1 16.1 40.5 15.8 29.9 29.5 40.7 36.6
 31.5  nan 12.1 25.5 22.3 27.1 44.7 26.1 18.8 18.7 24.8 17.  37.6 20.6
 29.  56.2 30.7 25.3 23.  27.2 19.2 31.6 24.6 27.  24.5 18.2 52.  32.3
 42.7 30.  24.3 24.2 25.7 36.7 46.4 48.3 20.9 24.7 23.6 26.5 39.4 18.4
 25.6 25.9 54.6 31.9 14.6 38.7 23.7 27.3 29.2 39.7 30.1 28.1 35.7 14.3
 30.4 22.2 35.  44.5 36.3 25.2 26.6 31.4 36.8 25.8 38.4 43.2 20.4 30.6
 33.8 34.  26.2 29.6 30.2 22.9 38.9 16.3 23.3 25.1 34.1 45.7 37.3 26.4
 40.9 31.1 17.7 27.5 19.9 32.  35.9 32.1 24.9 23.8 18.  20.7 27.7 22.6
 13.1 19.4 28.5 28.8 21.7 19.6 27.8 41.  41.8 35.2 44.4 42.6 15.7 52.8
 23.1 38.5 22.7 18.3 42.3 43.4 51.5 24.  28.7 23.9 37.9 32.6 35.6 34.7
 28.3 33.2 32.5 44.1 34.2 22.  33.3 16.8 35.4 20.1 26.3 37.5 33.1 21.2
 33.  33.6 30.3 26.  34.8 31.8 42.4 25.4 23.2 19.3 27.9 36.1 43.  16.9
 20.5 33.9 28.2 24.1 41.1 32.2 26.8 30.8 22.5 29.7 40.  34.5 28.  37.7
 19.8 28.4 34.3 20.8 16.2 17.5 36.9 19.5 31.7 34.4 29.1 39.3 35.5 21.
 31.  25.  20.3 17.9 36.5 47.5 19.  23.5 38.8 39.5 22.1 30.5 29.4 32.4
 16.7 22.8 16.4 24.4 54.8 19.1 39.2 18.5 28.6 48.2 41.2 20.  34.6 36.4
 29.8 59.7 14.4 28.9 27.6 19.7 32.8 44.8 21.1 16.6 14.9 18.9 17.1 20.2
 33.7 38.2 55.6 21.5 32.9 40.3 18.1 38.6 15.1 41.5 21.9 39.6 42.  13.7
 38.  41.3 35.3 48.6 41.7 21.3 47.6 30.9 61.1 31.3 38.3 37.2 35.8 49.1
 33.5 18.6 44.3 26.9 17.2 31.2 44.  49.8 39.1 39.8 39.9 17.3 22.4 21.4
 40.2 33.4 56.5 37.4 17.4 16.5 21.6 41.4 37.  36.  43.7 13.3 17.8 14.8
 39.  40.8 48.4 43.8 63.6 36.2 42.5 40.1 43.9 15.4 13.2 43.5 58.7 14.
 46.8 43.6 37.8 46.3 45.4 15.2 17.6 32.7 46.1 42.1 58.5 45.9 41.9 50.7
 54.  21.8 47.  66.1 45.3 34.9 42.2 55.7 55.1 45.1 52.7 16.  54.2 40.6
 49.9 13.8 53.4 46.9 55.8 45.6 43.3 15.3 77.9 47.3 38.1 57.9 53.6  9.6
 15.5 49.2 45.  49.5 12.8 62.6 43.1 12.2 56.8 45.2 51.9 52.1 62.5 47.8
 51.3 45.5 10.9 47.4 49.7 49.4 48.  50.8 52.4 45.8 97.  13.6 48.9 57.3
 14.5 40.4 47.9 50.5 12.6 14.1 57.4 42.8 49.3 46.2 48.7 58.4 53.3 55.
 46.5 53.1 51.8 50.3 53.9 58.1 13.  52.2 15.9 13.9 51.  51.4 57.6 46.7
 53.  15.  14.7]
['never smoked' 'smokes' 'Unknown' 'formerly smoked']
['No' 'Yes']

## Q2. What is the total number of missing or unknown values in the column Gender?

In [9]:
data['Gender'].unique()

array(['Female', 'Male', 'Unknown'], dtype=object)

In [10]:
data['Gender'].replace('Unknown', np.nan).isnull().sum()

np.int64(7)

## Q3. What is the total number of missing or unknown values in the column Age?

In [11]:
data[data['Age'] < 0].shape

(8, 11)

## Q4. What is the total number of missing or unknown values in the column GlucoseLevel?

In [12]:
data['GlucoseLevel'].unique()

array([ 54.6, 108.8,  64.1, ..., 218.9,  66.3, 168.5])

In [13]:
data['GlucoseLevel'].isnull().sum()

np.int64(0)

## Q5. What is the total number of missing or unknown values in the column LivesIn?

In [14]:
data['LivesIn'].unique()

array(['City', 'Village', 'Unknown'], dtype=object)

In [15]:
data['LivesIn'].replace('Unknown', np.nan).isnull().sum()

np.int64(5)


## Q6. What is the total number of missing or unknown values in the column BMI?

In [16]:
data['BMI'].isnull().sum()

np.int64(149)

## Q7. What is the total number of missing or unknown values in the column SmokingStatus?

In [17]:
data['SmokingStatus'].unique()

array(['never smoked', 'smokes', 'Unknown', 'formerly smoked'],
      dtype=object)

In [18]:
data['SmokingStatus'].replace('Unknown', np.nan).isnull().sum()

np.int64(1204)

## Q8. What is the mean value of the BMI in the dataset? Ignore the missing values if any

In [19]:
data['BMI'].isnull().sum()

np.int64(149)

In [20]:
print(data['BMI'].mean())

28.857958971695663

## Q9. How many people live in city, smoked at least once in life and had a heartattack? Ignore records/rows with any missing values.

In [21]:
data['Age'].replace(-3, np.nan, inplace=True)

<ipython-input-21-cbd660cbdf4e>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].replace(-3, np.nan, inplace=True)

In [22]:
data.replace('Unknown', np.nan, inplace=True)

In [23]:
data.isnull().sum()

Gender                7
Age                   8
HasTension            0
AnyHeartDisease       0
NeverMarried          0
Occupation            0
LivesIn               5
GlucoseLevel          0
BMI                 149
SmokingStatus      1204
HeartAttack           0
dtype: int64

In [24]:
df = data.dropna()

In [25]:
df.isnull().sum()

Gender             0
Age                0
HasTension         0
AnyHeartDisease    0
NeverMarried       0
Occupation         0
LivesIn            0
GlucoseLevel       0
BMI                0
SmokingStatus      0
HeartAttack        0
dtype: int64

In [26]:
data[(data['LivesIn']=='City') & (data['SmokingStatus'] != 'never smoked') & (data['HeartAttack']=='Yes')].shape

(73, 11)

## Q10. Which of the following categories have highest frequency? Ignore rows with missing values.


* female patients without tension, without any heart disease and never married

* female patients without tension, without any heart disease and either currently married or married before

* male patients without tension, without any heart disease and never married

* male patients with tension, with a heart disease and never married

* There is a tie between 2 or more options.

1. female patients without tension, without any heart disease and never married

In [27]:
data[(data['Gender'] == 'Female') & (data['HasTension']=='No') & (data['AnyHeartDisease'] == 'No') & (data['NeverMarried']== 'Yes')]

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation,LivesIn,GlucoseLevel,BMI,SmokingStatus,HeartAttack
1,Female,49.0,No,No,Yes,Private,Village,108.8,26.7,smokes,No
5,Female,NaN,No,No,Yes,Private,Village,83.2,29.3,smokes,No
8,Female,45.0,No,No,Yes,Private,City,64.6,40.5,never smoked,No
9,Female,52.0,No,No,Yes,Private,Village,67.5,15.8,NaN,No
10,Female,45.0,No,No,Yes,Self-employed,City,110.6,29.9,never smoked,No
...,...,...,...,...,...,...,...,...,...,...,...
3990,Female,45.0,No,No,Yes,Private,Village,89.4,21.3,formerly smoked,No
3991,Female,55.0,No,No,Yes,Private,City,83.4,22.8,NaN,No
3992,Female,46.0,No,No,Yes,Private,City,62.2,27.3,NaN,No
3995,Female,40.0,No,No,Yes,Private,City,88.4,36.5,smokes,No
3999,Female,58.0,No,No,Yes,Private,Village,59.2,27.9,formerly smoked,Yes

2. female patients without tension, without any heart disease and either currently married or married before

In [28]:
data[(df['Gender']== 'Female') & (data['HasTension']=='No') & (data['AnyHeartDisease']== 'No') & (data['NeverMarried']== 'No')]

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation,LivesIn,GlucoseLevel,BMI,SmokingStatus,HeartAttack
21,Female,29.0,No,No,No,Private,City,57.3,26.1,never smoked,No
28,Female,51.0,No,No,No,Private,Village,66.7,29.0,never smoked,No
29,Female,26.0,No,No,No,Private,City,116.4,18.8,formerly smoked,No
42,Female,65.0,No,No,No,Self-employed,Village,87.2,32.3,never smoked,No
46,Female,19.0,No,No,No,Never_worked,City,86.8,25.5,never smoked,No
...,...,...,...,...,...,...,...,...,...,...,...
3946,Female,50.0,No,No,No,Private,City,85.9,21.8,never smoked,No
3948,Female,18.0,No,No,No,Private,Village,99.0,22.4,never smoked,No
3976,Female,22.0,No,No,No,Private,City,140.0,20.6,never smoked,No
3996,Female,18.0,No,No,No,Private,Village,168.5,48.2,never smoked,No
3998,Female,28.0,No,No,No,Private,City,80.0,27.1,smokes,No

3. male patients without tension, without any heart disease and never married

In [29]:
data[(data['Gender']=='Male') & (data['HasTension']=='No') & (data['AnyHeartDisease']== 'No') & (data['NeverMarried']== 'Yes')]

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation,LivesIn,GlucoseLevel,BMI,SmokingStatus,HeartAttack
2,Male,32.0,No,No,Yes,Private,City,64.1,23.4,smokes,No
3,Male,78.0,No,No,Yes,Self-employed,City,219.2,27.4,NaN,Yes
4,Male,39.0,No,No,Yes,Private,City,55.4,41.6,formerly smoked,No
6,Male,63.0,No,No,Yes,Private,City,104.1,37.1,formerly smoked,No
11,Male,31.0,No,No,Yes,Private,Village,101.4,29.5,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...
3982,Male,47.0,No,No,Yes,Govt_job,City,66.3,32.3,never smoked,No
3983,Male,77.0,No,No,Yes,Private,City,223.0,29.6,formerly smoked,No
3989,Male,37.0,No,No,Yes,Govt_job,Village,72.5,34.9,never smoked,No
3993,Male,71.0,No,No,Yes,Private,City,85.4,28.3,never smoked,No
3997,Male,27.0,No,No,Yes,Private,City,76.5,21.0,never smoked,No

4. male patients with tension, with a heart disease and never married

In [30]:
data[(data['Gender']=='Male') & (data['HasTension']=='No') & (data['AnyHeartDisease']=='Yes') & (data['NeverMarried']=='Yes')]

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation,LivesIn,GlucoseLevel,BMI,SmokingStatus,HeartAttack
131,Male,82.0,No,Yes,Yes,Private,Village,208.3,31.1,NaN,Yes
172,Male,72.0,No,Yes,Yes,Self-employed,City,85.5,23.1,formerly smoked,No
252,Male,78.0,No,Yes,Yes,Private,City,218.1,NaN,NaN,Yes
275,Male,53.0,No,Yes,Yes,Private,Village,94.5,33.6,smokes,No
310,Male,64.0,No,Yes,Yes,Private,Village,109.2,34.5,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...
3722,Male,72.0,No,Yes,Yes,Self-employed,Village,97.2,30.8,smokes,No
3888,Male,76.0,No,Yes,Yes,Private,City,79.2,NaN,NaN,No
3891,Male,73.0,No,Yes,Yes,Private,Village,81.6,32.9,formerly smoked,No
3926,Male,71.0,No,Yes,Yes,Private,Village,70.9,24.4,smokes,No
3938,Male,68.0,No,Yes,Yes,Private,City,218.9,24.8,NaN,No

## Q11. Select columns with categorical values :

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           3993 non-null   object
 1   Age              3992 non-null   float64
 2   HasTension       4000 non-null   object
 3   AnyHeartDisease  4000 non-null   object
 4   NeverMarried     4000 non-null   object
 5   Occupation       4000 non-null   object
 6   LivesIn          3995 non-null   object
 7   GlucoseLevel     4000 non-null   float64
 8   BMI              3851 non-null   float64
 9   SmokingStatus    2796 non-null   object
 10  HeartAttack      4000 non-null   object
dtypes: float64(3), object(8)
memory usage: 343.9+ KB

## Q12. 'HeartAttack' is the target column. What is the distribution count of "No" and "Yes" classes?

In [32]:
data['HeartAttack'].value_counts()

HeartAttack
No     3806
Yes     194
Name: count, dtype: int64

## Q13. Divide the data into training and test sets
Keep 30% of the data as test set.

Use random_state as 0

HeartAttack is the target, rest of the columns are the features.

 For the label/target vector, replace "Yes" with 1 and "No" with 0.

 Divide the dataset into training and test sets keeping target(y) in stratified manner.

Hint: look for the documentation of the usual function that divides the data into training and test datasets.

In [33]:
X=data.drop(columns=['HeartAttack'])
Y=data['HeartAttack']

In [34]:
y=Y.replace(['Yes', 'No'], [1,0])

<ipython-input-34-c875a5b65e02>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y=Y.replace(['Yes', 'No'], [1,0])

In [35]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=0)   #we can take a number of combinations of splits but here we are interested in only One combination of split.
for train, test in split.split(X,y):
  X_train = X.iloc[train]
  X_test = X.iloc[test]
  y_train = y.iloc[train]
  y_test = y.iloc[test]

Prepare a data preprocessing pipeline to process features in following order:

Gender: Impute with most frequent then ordinally encode.

Age: Impute with mean then standard scale.

HasTension: Ordinally encode.

AnyHeartDisease:Ordinally encode.

NeverMarried:Ordinally encode.

Occupation: One hot encode.

LivesIn: Impute with most frequent then ordinally encode.

GlucoseLevel: Impute with mean, then min-max scaling.

BMI: Impute with mean, then standard scale.

SmokingStatus: Impute with most frequent, then one hot encode

Hint: After transformation, your feature matrix must have columns in following order:

0. Gender

1. Age
2. HasTension
3. AnyHeartDisease
4. NeverMarried
5. Occupation_Govt_job
6. Occupation_Never_worked
7. Occupation_Private
8. Occupation_Self-employed
9. Occupation_children
10. LivesIn
11. GlucoseLevel
12. BMI
13. SmokingStatus_formerly smoked
14. SmokingStatus_never smoked
15. SmokingStatus_smokes

NOTE:

Make sure to preprocess the features in the above order exactly. Answer(s) of later question(s) depend(s) upon correct order of featuring processing.
You may have to use multiple instances of a trasnformer for this question.

In [36]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [37]:
col= ColumnTransformer([
    ('gender',
     Pipeline([
         ('scaled', SimpleImputer(strategy='most_frequent')),
         ('ordinal', OrdinalEncoder())]),
                                        ['Gender']),
    ('age',
     Pipeline([
         ('impute', SimpleImputer(strategy='mean')),
         ('scaled', StandardScaler())
     ]),  ['Age']),

    ('ordinal', OrdinalEncoder(), ['HasTension']),
    ('ordinal2', OrdinalEncoder(), ['AnyHeartDisease']),
    ('ordinal3', OrdinalEncoder(), ['NeverMarried']),
    ('onehotencode', OneHotEncoder(), ['Occupation']),
    ('livesin',
     Pipeline([
         ('impute2', SimpleImputer(strategy='most_frequent')),
         ('ordinal4', OrdinalEncoder())
     ]), ['LivesIn']),
    ('glucoselevel',
     Pipeline([
         ('impute3', SimpleImputer(strategy='mean')),
         ('scaled2', MinMaxScaler())
     ]),  ['GlucoseLevel']),
    ('bmi',
     Pipeline([
         ('impute4', SimpleImputer(strategy='mean')),
         ('scaled3', StandardScaler())
     ]), ['BMI']),
    ('smokingstatus',
     Pipeline([
         ('impute5', SimpleImputer(strategy='most_frequent')),
         ('onehotencode2', OneHotEncoder())
     ]), ['SmokingStatus'])
], remainder='passthrough', verbose_feature_names_out=False)

In [38]:
preprocess= col.fit_transform(X_train)

In [39]:
data= pd.DataFrame(preprocess, columns=col.get_feature_names_out())

In [40]:
data.head()

,Gender,Age,HasTension,AnyHeartDisease,NeverMarried,Occupation_Govt_job,Occupation_Never_worked,Occupation_Private,Occupation_Self-employed,Occupation_children,LivesIn,GlucoseLevel,BMI,SmokingStatus_formerly smoked,SmokingStatus_never smoked,SmokingStatus_smokes
0,0.0,0.433901,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.366568,0.284421,0.0,1.0,0.0
1,1.0,-1.840435,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.511861,-1.186687,0.0,1.0,0.0
2,1.0,-1.160260,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.464789,0.065045,0.0,1.0,0.0
3,1.0,-0.806002,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.349889,0.929643,0.0,1.0,0.0
4,0.0,0.743876,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.364344,-0.412420,0.0,0.0,1.0

## Calculate the shape of the feature matrix of training dataset.

In [41]:
data.shape

(2800, 16)